### ISSUE TITLE
[REFACTOR] 전체적인 도메인 엔티티 변경

### ISSUE THREAD

**Issue by catturtle123** [SMUING-D/BE-SMUING#4]
## Description
전체적인 도메인 엔티티 변경

## To-do
- [x] 대댓글 테이블 삭제
- [x] comment 엔티티 자기 참조 추가 및 필드 추가
- [x] user 엔티티 필드 추가
- [x] study, community 엔티티 사진 테이블 추가
