### ISSUE TITLE
[FEAT] 에러 설정 추가

### ISSUE THREAD

**Issue by catturtle123** [SMUING-D/BE-SMUING#7]
## Description
에러 설정 추가

## To-do
- [x] 에러 핸들러 추가
- [x] 에러 코드 추가
- [x] 에러 response 추가
